spring:
  datasource:
    url: jdbc:mysql://192.168.100.130/springboot_jpa?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=true
    username: root
    password: proaim
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      # 更新 or 创建数据表结构
      ddl-auto: update
    # 控制台显示SQL语句
    show-sql: true