spring:
  datasource:
    url: jdbc:mysql://192.168.100.110:3300/springboot_mybatis?characterEncoding=utf-8
    username: root
    password: proaim@2019
    driver-class-name: com.mysql.cj.jdbc.Driver
  profiles:
    active: test

# Mybatis配置
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.proaimltd.mybatis.model.entity
  configuration:
    # 使用jdbc的getGeneratedKeys 可以获取数据库自增主键值
    use-generated-keys: true
    # 开启驼峰命名转换，如：Table(create_time) -> Entity(createTime)。不需要我们关心怎么进行字段匹配，mybatis会自动识别`大写字母与下划线`
    map-underscore-to-camel-case: true

# PageHelper配置
pagehelper:
  helperDialect: mysql
  reasonable: true
  rowBoundsWithCount: true
  supportMethodsArguments: true
  params: count=countSql
  # 查询所有记录总数（并不是当前页）
  dialect: com.github.pagehelper.dialect.helper.MySqlDialect
